# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://localhost:8086
    database: telegraf
    user: telegraf
    password: telegraf
    is_default: true
    editable: true
